title: builderscon
description: > 
  builderscon is a festival for the technology lovers.
blogurl: http://blog.builderscon.io
mainurl: http://builderscon.io
twitter_username: builderscon
github_username:  builderscon
fb_app_id: 1537973726511652
fb_page_id: 1233910219973110

markdown: kramdown